name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Utilisez la version de Node.js appropriée pour votre application

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation des dépendances
        run: cd api && npm install

      - name: Build de l'application
        run: cd api && npm run build

      - name: Déploiement sur le serveur FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: ./src/dist/ # Assurez-vous que c'est le bon chemin pour vos fichiers construits
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
# Ajoutez d'autres étapes de déploiement si nécessaire, par exemple, un déploiement sur un serveur de production, des notifications, etc.
